### ISSUE TITLE
Use fs 2.4.9?

### ISSUE THREAD

**Issue by chfw** [althonos/jinja2-fsloader#4]
Hi @althonos,

Current jinja2-fsloader has version limiation: `fs >=2.1.0,<2.3.0`. Is there a particular reason to limit its upper version? Can it use any version beyond 2.3.0?

Thanks

**Comment by althonos** [comment]
I wasn't sure about compatibility because `fs 2.3.0` broke a lot of things, but it may work fine, I'll have to test.

**Comment by althonos** [comment]
Just tested with latest `fs` and nothing seem to explode, so I'll push a new release whenever I can.
